/**
 * 
 */
package com.dafrito.rfe;

enum DebugString {
	ELEMENTS,
	SCRIPTGROUPPARENTHETICAL,
	SCRIPTGROUPCURLY,
	NUMERICSCRIPTVALUESHORT,
	NUMERICSCRIPTVALUEINT,
	NUMERICSCRIPTVALUELONG,
	NUMERICSCRIPTVALUEFLOAT,
	NUMERICSCRIPTVALUEDOUBLE,
	PERMISSIONNULL,
	PERMISSIONPRIVATE,
	PERMISSIONPROTECTED,
	PERMISSIONPUBLIC,
	SCRIPTLINE,
	SCRIPTOPERATOR,
	ORIGINALSTRING,
	REFERENCEDELEMENTNULL,
	OUTPUTTREE
}