package com.dafrito.logging;

public enum CachedStrings {
	ELEMENTS,
	SCRIPTGROUPPARENTHETICAL,
	SCRIPTGROUPCURLY,
	NUMERICSCRIPTVALUESHORT,
	NUMERICSCRIPTVALUEINT,
	NUMERICSCRIPTVALUELONG,
	NUMERICSCRIPTVALUEFLOAT,
	NUMERICSCRIPTVALUEDOUBLE,
	PERMISSIONNULL,
	PERMISSIONPRIVATE,
	PERMISSIONPROTECTED,
	PERMISSIONPUBLIC,
	SCRIPTLINE,
	SCRIPTOPERATOR,
	ORIGINALSTRING,
	REFERENCEDELEMENTNULL,
	OUTPUTTREE
}
